# -*- coding: utf-8 -*-
"""Financial_Health_Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K3CvXcd1Xxd5scn3DBuMz_fS6eO3E3WU
"""

import yfinance as ticker_data

#This project uses the yfinance library to analyze Apple's liquidity and profitability ratios, based on the CFA Level 1 syllabus

# 1. Definir a empresa (Exemplo: Apple - AAPL)
empresa = ticker_data.Ticker("AAPL")
print("Analisando Saúde Financeira da Apple...")

# 2. Balanço Patrimonial e a DRE
balanco = empresa.balance_sheet
dre = empresa.financials

# 3. Extrair termos técnicos (Usando dados do último ano)
current_assets = balanco.loc['Current Assets'].iloc[0]
current_liabilities = balanco.loc['Current Liabilities'].iloc[0]
net_income = dre.loc['Net Income'].iloc[0]
revenue = dre.loc['Total Revenue'].iloc[0]

# 4. Cálculos de Investment Banking
current_ratio = current_assets / current_liabilities  # Liquidez Corrente
net_profit_margin = (net_income / revenue) * 100      # Margem de Lucro Líquida

# 5. Output
print(f"--- Relatório de Análise ---")
print(f"Current Ratio: {current_ratio:.2f} (CFA diz: > 1.0 é saudável)")
print(f"Net Profit Margin: {net_profit_margin:.2f}%")

#6 Calculando ROE:
equity = balanco.loc['Stockholders Equity'].iloc[0]
roe = (net_income / equity) * 100
print(f"ROE: {roe:.2f}%")

if current_ratio > 1.5:
    print("Veredito: Forte Liquidez de Curto Prazo.")
else:
    print("Veredito: Atenção necessária na Liquidez.")